spring:
    datasource:
        driverClassName: org.h2.Driver
        password: ''
        url: jdbc:h2:mem:mydb
        username: sa
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
logging.level.org.hibernate.SQL: TRACE
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE
logging.level.org.springframework.jdbc.core.JdbcTemplate: TRACE
logging.level.org.springframework.jdbc.core.StatementCreatorUtils: TRACE

camel:
    springboot:
        shutdownTimeout: 1
        health.indicator.enabled: true
